### ISSUE TITLE
Flow trigger with http request

### ISSUE THREAD

**Issue by cpluceDev** [MakingThingsWorkToronto/mtw-search-extensibility#2]
I am trying to use the flow trigger feature which keeps failing. what would be the data-body? This is my trigger. I have tested my trigger in the browser and it works. just fails using this extensibility.  if i can get this to work by passing in the employee id for that search result, this would be awesome. thanks 
This is my request body json in the trigger and it is a get. 

`{
    "type": "object",
    "properties": {
        "EmployeeId": {
            "type": "integer"
        }
    }
}`

**Comment by thastarkmtw** [comment]
Unfortunately this will only support POST requests, I can expose the method as a parameter if that would help. I didn't do a very good job documenting this one.  The flow needs to return the following object for the button to work:

// FAILURE RESPONSE
{
  "success": false,
  "status": "Failure message goes here"
}

// SUCCESS RESPONSE
{
  "success": true,
  "status": "Success message goes here"
}

**Comment by cpluceDev** [comment]
i tired post but that didnt work either

**Comment by cpluceDev** [comment]
can you provide more info on configuration

**Comment by cpluceDev** [comment]
i think it might be the column type for multiple line of text. need to change from enhanced to plain text. will test now

**Comment by cpluceDev** [comment]
ideally. i would like to trigger the flow from side panel and pass employee id to flow which does some actions. thx

**Comment by thastarkmtw** [comment]
Please share the configuration of the tag. Thx

**Comment by cpluceDev** [comment]
`<mtw-flow-button data-title="Generate Resume" data-icon="Play"
 data-endpoint="[copied url from trigger and pasted here]"
 data-body="{&#x22;ItemIndex&#x22;: &#x22;{{EmployeeId}}&#x22;}" 
 data-success="The flow run was successful"
 data-failure="The flow run failed" 
 data-class-name="action-button-custom-css-class" 
 data-success-class="success-message-custom-css-class"
 data-failure-class="failure-message-custom-css-class">
</mtw-flow-button>`

side question; is it possible to enable copy and paste the text from the side panel

**Comment by cpluceDev** [comment]
nevermind side question. looks like it works on my end. might be on  user end of the browser limitation

**Comment by cpluceDev** [comment]
i do have another flow where it does trigger a child flow based on this same trigger and passing the item index. but im using an http action to achieve that.  this trigger is also a POST. thx same principle but not triggered with a link. it is triggered from another flow http action

**Comment by cpluceDev** [comment]
the flow actually gets triggered fro mthe flow link in the side panel. i just get a failed message because i am not retuning the success response.  have any info on these steps? 
thx

**Comment by cpluceDev** [comment]
do i have to edit the tag configuration? this is my flow and it does get triggered. but the tag displays the failed status message. how can i get the success message to display? thx

![image](https://user-images.githubusercontent.com/25770942/93549110-39b20000-f92e-11ea-84e2-0338837af7a1.png)

**Comment by cpluceDev** [comment]
i think i am  making some progress but still could use some assistance. thx 
![image](https://user-images.githubusercontent.com/25770942/93656175-f4550780-f9ed-11ea-8b41-1850ad7b13dc.png)

**Comment by cpluceDev** [comment]
![image](https://user-images.githubusercontent.com/25770942/93656370-72fe7480-f9ef-11ea-80dd-c9d5e15c2a78.png)
resolved
