### ISSUE TITLE
updated to Project pnp-modern-search version:3.15.3 broke my extensibility

### ISSUE THREAD

**Issue by cpluceDev** [MakingThingsWorkToronto/mtw-search-extensibility#4]
i had to get the latest Project pnp-modern-search version:3.15.3. created a new local repository and uploaded new packaged solution. now this extensibility feature doesnt work or isnt recognized anymore. all the content is inside the result type and im not getting the link to open side panel.

**Comment by thastarkmtw** [comment]
Thanks for testing! Does the library connect if you add a new webpart? Are there any errors in the console? If you use the developer tools, can you take a look and see in the Source tab if the library is being loaded - you should see a file called MTW-extensibility-*.JS

**Comment by cpluceDev** [comment]
nope. the js is not loaded as a source. in the debugger. i compared it to the site  collectin where it is working and i see your project listed under cdn but isnt in my test and pretest environment. this is in the clientsideassets dir

**Comment by thastarkmtw** [comment]
I haven't tested 3.15.3 yet. Super busy but hopefully will get to it this week. To confirm, the extensibility library is deployed to the site collection?  

Are there any errors in the console?  If you create a new page and add the results web part there is it loading OK?

**Comment by cpluceDev** [comment]
false alarm. i figured it out. i thought i had this solution deployed to this site collection. when i deployed the app it worked. it had the old demo ext solution installed and was using that
